### ISSUE TITLE
R2 tracking issue

### ISSUE THREAD

**Issue by hgzimmerman** [hgzimmerman/SWEN344-web-project#120]
- [ ] Current Weather
  * The user should be able to customize their location for the weather: They should be able to enter their zip code for the user to enter in their location. The system should save the user's zip code preference (which they can change at any time.) When the user logs out and logs back in then this information should persist.
* Two main additions for functionality include:
  - [ ] Stock ticker (Storing information)
  - [ ] Calendar (Storing information)
  - [ ] Other items as will be defined by customer,

* Testing
  - [ ] UI Tester
  - [ ] Updated Bug Tracker

* Documentation.
  * Small .pdf document containing: 
    - [ ] Your version control system link & any appropriate logins
    - [ ] Analytics feature for customer. You will need to elicit the precise details with the customer. Something like Google Analytics here is fine.

- [ ] A fully implemented system with good usability.
- [ ] Your staging & production environments should be mirrors of each other. (We don't have a staging environment)
- [ ] Create a virtual directory for the release titled R2. If you are using a different technology than .Net, then do something analogous (you are encouraged to speak about this with your instructor). This means that the release should be http://vm549-x.se.rit.edu/R2/
- [ ] You may leave all of your source code in your Version Control System. There is no need to submit the code.
- [ ] All data should be stored in your database. Do not plan on storing anything in local files (IE .csv or .xml files)
- [ ] Everything should be as functional as possible. Additionally, the application should be much more aesthetically pleasing.

* Database
  - [ ] Schema
  - [ ] Propagation mechanism
  - [ ] Functionality
  - [ ] Security (you can discuss this with customer)
    - [ ] Tools ran to assess security risks and their results. Additionally, you should provide a mitigation plan for how you would deal with the risks (it will take some research and planning on your part).
    - [ ] At least 5 Abuse and Misuse cases.
    - [ ] Main areas of vulnerability for your project.

* Application should work in:
  - [ ] Internet Explorer
  - [ ] FireFox
  - [ ] Various versions of Chrome

**Comment by hgzimmerman** [comment]
The section for R2 did leave out some requirements.

- [ ] Self-adaptive requirement
