### ISSUE TITLE
R1 Tracking Issue

### ISSUE THREAD

**Issue by hgzimmerman** [hgzimmerman/SWEN344-web-project#31]
- [x] Weather: The page should show the current weather for RIT (14623)
 ###  Proper development  & "production" environment setup.
- [x] Virtual machines
- [x] Calendar - (No need to store information that is an R2 requirement)
- [x] Bug Tracking
  * How many bugs did you collect
  * How many open bugs do you have? And why are they open
  * How has the bug collection/mitigation process helped or hurt your project
  * This can all be placed into a small pdf.
- [x] Version control system
  * If you use GitHub, please give me access (dan7800)
- [x] Main page setup
- [ ] Facebook/Twitter tie in
- [x] My test account is dxkvse@rit.edu so please add this to your FaceBook/Twitter app/project if necessary.
- [x] You MAY need to add me as a test user.
- [x] You may also create a test Facebook user. If you do, provide the approriate login/password in your documentation.
- You may leave all of your source code in your Version Control System. There is no need to submit.
- [x] Small .pdf document containing:  Your version control system link & any appropriate logins
###### Stock ticker (Retrieve information from existing external API's)
- [x] You should have a stock page for any ticket symbols that the user may "punch in". Displayed data should include:
  * Current price
  * Day's high
  * Day's low
  * Yearly high
  * Yearly low
- [x] An interactive chart of the stock (not just a retrieved image)
###### Updated documentation (design & requirements).
- [x] This includes updates & necessary additions to all documents.

- [x] Make sure that your website is publicly accessible to the outside world. This is required for the 1st deliverable and I encourage you to test your application early & often.
* "Final" deliverable is on the production website.

###### Testing
- [x] Basic Set up of UI Tester (Selenium, iMacros etc...) Basically, just show that you are working towards implementing this for R2. A screen shot of this implementation (in a .pdf form) is fine.
- [x] Other items as will be defined by customer.
- [x] You DO NOT need to set up a SQL Database for R1.
##### A Document with the following:
- [x] Your site URL
- [x] Login information on your site. Please provide me with "dummy" login information needed to access your site (if applicable).
- [x] A brief readme

**Comment by hgzimmerman** [comment]
R1 delivered
